/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sapient.client.gui;

import java.math.BigDecimal;
import java.sql.*;

import javax.swing.JOptionPane;

/**
 * 
 * @author csin16
 */
public class EmployeeDetails extends javax.swing.JFrame {

	/**
	 * Creates new form EmployeeDetails
	 */
	public EmployeeDetails() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lblEmployeeID = new javax.swing.JLabel();
		lblFirstName = new javax.swing.JLabel();
		lblLastName = new javax.swing.JLabel();
		lblSalary = new javax.swing.JLabel();
		txtEmployeeID = new javax.swing.JTextField();
		txtFirstName = new javax.swing.JTextField();
		txtLastName = new javax.swing.JTextField();
		txtSalary = new javax.swing.JTextField();
		findbyID = new javax.swing.JButton();
		Add = new javax.swing.JButton();
		Modify = new javax.swing.JButton();
		Remove = new javax.swing.JButton();
		exit = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lblEmployeeID.setText("Employee ID");

		lblFirstName.setText("First Name");

		lblLastName.setText("Last Name");

		lblSalary.setText("Salary");

		findbyID.setText("Find by ID");
		findbyID.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				findbyIDActionPerformed(evt);
			}
		});

		Add.setText("Add");
		Add.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AddActionPerformed(evt);
			}
		});

		Modify.setText("Modify");
		Modify.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ModifyActionPerformed(evt);
			}
		});

		Remove.setText("Remove");
		Remove.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				RemoveActionPerformed(evt);
			}
		});

		exit.setText("Exit");
		exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(22, 22, 22)
								.addComponent(findbyID)
								.addGap(22, 22, 22)
								.addComponent(Add)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										30, Short.MAX_VALUE)
								.addComponent(Modify).addGap(27, 27, 27)
								.addComponent(Remove).addGap(23, 23, 23))
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(38, 38,
																		38)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						lblEmployeeID)
																				.addComponent(
																						lblFirstName)
																				.addComponent(
																						lblLastName)
																				.addComponent(
																						lblSalary))
																.addGap(71, 71,
																		71)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						txtEmployeeID,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						178,
																						Short.MAX_VALUE)
																				.addComponent(
																						txtFirstName)
																				.addComponent(
																						txtLastName)
																				.addComponent(
																						txtSalary)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(161,
																		161,
																		161)
																.addComponent(
																		exit)))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(25, 25, 25)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblEmployeeID)
												.addComponent(
														txtEmployeeID,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(27, 27, 27)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblFirstName)
												.addComponent(
														txtFirstName,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(27, 27, 27)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblLastName)
												.addComponent(
														txtLastName,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(30, 30, 30)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblSalary)
												.addComponent(
														txtSalary,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(38, 38, 38)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(findbyID)
												.addComponent(Add)
												.addComponent(Modify)
												.addComponent(Remove))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										16, Short.MAX_VALUE).addComponent(exit)
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void findbyIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_findbyIDActionPerformed
		// TODO add your handling code here:
		CallableStatement cStatement = null;
		Connection dbConnection = null;

		try {
			DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());

			dbConnection = DriverManager.getConnection(
					"jdbc:oracle:thin:@deltahiti31202:1521:XE", "Charul",
					"charul123");

			cStatement = dbConnection.prepareCall("{call query_emp(?,?,?,?)}");

			cStatement.setInt(1, Integer.parseInt(txtEmployeeID.getText()));

			cStatement.registerOutParameter(2, java.sql.Types.VARCHAR);
			cStatement.registerOutParameter(3, java.sql.Types.VARCHAR);
			cStatement.registerOutParameter(4, java.sql.Types.DECIMAL);

			cStatement.execute();

			String empFirstName = cStatement.getString(2);
			String empLastName = cStatement.getString(3);
			BigDecimal empSal = cStatement.getBigDecimal(4);
			txtFirstName.setText(empFirstName);
			txtLastName.setText(empLastName);
			txtSalary.setText(empSal.toString());
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		/*
		 * Connection dbConnection=null; PreparedStatement pStatement=null;
		 * ResultSet result=null; try { DriverManager.registerDriver(new
		 * oracle.jdbc.driver.OracleDriver());
		 * dbConnection=DriverManager.getConnection
		 * ("jdbc:oracle:thin:@deltahiti31202:1521:XE", "Charul", "charul123");
		 * 
		 * 
		 * pStatement=dbConnection.prepareStatement(
		 * "SELECT  FIRST_NAME,LAST_NAME,SALARY FROM EMPJDBC WHERE EMPLOYEE_ID=?"
		 * ); pStatement.setInt(1,Integer.parseInt(txtEmployeeID.getText()));
		 * result=pStatement.executeQuery(); if( result.next()){
		 * txtFirstName.setText(result.getString(1));
		 * txtLastName.setText(result.getString(2));
		 * txtSalary.setText(result.getString(3)); } else{
		 * JOptionPane.showMessageDialog(this,
		 * "no record found","Emplotyee id does not exist"
		 * ,JOptionPane.ERROR_MESSAGE);
		 * 
		 * }} catch(SQLException e){ e.printStackTrace(); }
		 * 
		 * finally{ try{ if(dbConnection!=null && !dbConnection.isClosed()) {
		 * dbConnection.close();
		 * 
		 * } if(pStatement!=null ) { pStatement.close();
		 * 
		 * } if(result!=null ) { result.close();
		 * 
		 * }}catch(SQLException e){ e.printStackTrace(); } }
		 */
	}

	// GEN-LAST:event_findbyIDActionPerformed

	private void AddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AddActionPerformed
		// TODO add your handling code here:
		Connection dbConnection = null;
		PreparedStatement pStatement = null;

		try {
			DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
			dbConnection = DriverManager.getConnection(
					"jdbc:oracle:thin:@deltahiti31202:1521:XE", "Charul",
					"charul123");
			pStatement = dbConnection
					.prepareStatement("INSERT INTO EMPJDBC VALUES(?,?,?,?)");

			pStatement.setInt(1, Integer.parseInt(txtEmployeeID.getText()));
			pStatement.setString(2, txtFirstName.getText());
			pStatement.setString(3, txtLastName.getText());
			pStatement.setInt(4, Integer.parseInt(txtSalary.getText()));
			int response = pStatement.executeUpdate();
			if (response != 0) {
				JOptionPane.showMessageDialog(this, "data has been inserted",
						"details has been inserted",
						JOptionPane.INFORMATION_MESSAGE);
			}

			else {
				JOptionPane.showMessageDialog(this, "data can't be inserted ",
						" ", JOptionPane.ERROR_MESSAGE);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}

		finally {
			try {
				if (dbConnection != null && !dbConnection.isClosed()) {
					dbConnection.close();

				}
				if (pStatement != null) {
					pStatement.close();

				}

			} catch (SQLException e) {
				e.printStackTrace();
			}
		}

	}// GEN-LAST:event_AddActionPerformed

	private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ModifyActionPerformed
		// TODO add your handling code here:
		Connection dbConnection = null;
		PreparedStatement pStatement = null;

		try {
			DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
			dbConnection = DriverManager.getConnection(
					"jdbc:oracle:thin:@deltahiti31202:1521:XE", "Charul",
					"charul123");
			pStatement = dbConnection
					.prepareStatement("UPDATE EMPJDBC SET FIRST_NAME=?,LAST_NAME=?,SALARY=? WHERE EMPLOYEE_ID=?");

			pStatement.setString(1, txtFirstName.getText());
			pStatement.setString(2, txtLastName.getText());
			pStatement.setInt(3, (Integer.parseInt(txtSalary.getText())));
			pStatement.setInt(4, (Integer.parseInt(txtEmployeeID.getText())));

			int response = pStatement.executeUpdate();
			if (response != 0) {
				JOptionPane.showMessageDialog(this, "data has been modified",
						" ", JOptionPane.INFORMATION_MESSAGE);
			}

			else {
				JOptionPane.showMessageDialog(this, "data can't be modify ",
						" ", JOptionPane.ERROR_MESSAGE);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}

		finally {
			try {
				if (dbConnection != null && !dbConnection.isClosed()) {
					dbConnection.close();
				}
				if (pStatement != null) {
					pStatement.close();

				}

			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
	}// GEN-LAST:event_ModifyActionPerformed

	private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RemoveActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_RemoveActionPerformed

	private void exitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_exitActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EmployeeDetails.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EmployeeDetails.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EmployeeDetails.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EmployeeDetails.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new EmployeeDetails().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton Add;
	private javax.swing.JButton Modify;
	private javax.swing.JButton Remove;
	private javax.swing.JButton exit;
	private javax.swing.JButton findbyID;
	private javax.swing.JLabel lblEmployeeID;
	private javax.swing.JLabel lblFirstName;
	private javax.swing.JLabel lblLastName;
	private javax.swing.JLabel lblSalary;
	private javax.swing.JTextField txtEmployeeID;
	private javax.swing.JTextField txtFirstName;
	private javax.swing.JTextField txtLastName;
	private javax.swing.JTextField txtSalary;
	// End of variables declaration//GEN-END:variables
}
